import { createInertiaApp } from '@inertiajs/react';
import createServer from '@inertiajs/react/server';
import ReactDOMServer from 'react-dom/server';
import { route } from 'ziggy-js';
// @ts-ignore — ziggy.js is generated by `artisan ziggy:generate`
import { Ziggy } from './ziggy';

createServer((page) =>
    createInertiaApp({
        page,
        render: ReactDOMServer.renderToString,
        // Title suffix is handled by <SEO> component per-page.
        title: (title) => title || 'Dina Kenitra FC',
        resolve: (name) => {
            const pages = import.meta.glob<{ default: unknown }>('./Pages/**/*.tsx', {
                eager: true,
            });
            return pages[`./Pages/${name}.tsx`];
        },
        setup: ({ App, props }) => {
            /* eslint-disable @typescript-eslint/no-explicit-any */
            (globalThis as any).route = (
                name: string,
                params?: any,
                absolute?: boolean
            ) =>
                route(name, params as any, absolute, {
                    ...(Ziggy as any),
                    location: new URL(props.initialPage.url, (Ziggy as any).url),
                });
            /* eslint-enable @typescript-eslint/no-explicit-any */

            return <App {...props} />;
        },
    })
);
